# -*- coding: utf-8 -*-
"""iPhone_sell_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dTjKTVTm7dEDc4u4okLPzrQfD2Z854Dm
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("apple_products.csv")

df.head()

df.info()

df.isnull().sum()

df.describe()

df = df.rename(columns= {
    "Ram": "Ram(in GB)",
    'Mrp': 'MRP',
    'Discount Percentage': 'Discount',
    'Number Of Ratings': 'Rating',
    'Number Of Reviews': 'Reviews',
    'Star Rating': 'Star'
})
print(type(df))

df.describe()

df.info()

df.head(5)

"""# iPhone sale price Analysis

"""

highest_rated = df.sort_values(by = ['Star'], ascending = False)

print(highest_rated.head(10))

iphone = highest_rated['Product Name'].value_counts()

plt.figure(figsize=(10,5))
sns.barplot(x=iphone.index, y=iphone.values)
plt.xticks(rotation=90)
plt.show()

